[package]
name = "dull"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
include_dir = "0.7.4"
serde_json = "1.0"
thiserror = "2.0.16"
schemars = "1.0.4"
